### ISSUE TITLE
Unparsed group '09008KT 7SM' when wind is listed after sky groups.

### ISSUE THREAD

**Issue by jhaiduce** [python-metar/python-metar#147]
The following METAR produces a ParserError:

METAR KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186

Backtrace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jhaiduce/Development/python-metar/metar/Metar.py", line 499, in __init__
    raise ParserError(message)
metar.Metar.ParserError: Unparsed groups in body '09008KT 7SM' while processing 'METAR KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186'
```

**Comment by jhaiduce** [comment]
Here's the output with debugging turned on:

```
DEBUG:metar.Metar:_handleType: METAR KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleType matched 'METAR '
DEBUG:metar.Metar:_handleCorrection: KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleStation: KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleStation matched 'KCOF '
DEBUG:metar.Metar:_handleTime: 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTime matched '281855Z '
DEBUG:metar.Metar:_handleModifier: FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWind: FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleVisibility: FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleRunway: FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWeather: FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSky: FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSky matched 'FEW029TCU '
DEBUG:metar.Metar:_handleSky: FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSky matched 'FEW040 '
DEBUG:metar.Metar:_handleSky: SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSky matched 'SCT250 '
DEBUG:metar.Metar:_handleSky: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePressure: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleRecent: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShear: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleColor: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleRunwayState: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTrend: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_startRemarks: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedGroup: 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedGroup matched '09008KT '
DEBUG:metar.Metar:_handleSky: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePressure: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleRecent: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShear: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleColor: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleRunwayState: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTrend: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_startRemarks: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedGroup: 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedGroup matched '7SM '
DEBUG:metar.Metar:_handleSky: 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp: 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp matched '32/25 '
DEBUG:metar.Metar:_handlePressure: A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePressure matched 'A3008 '
DEBUG:metar.Metar:_handlePressure: RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleRecent: RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShear: RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleColor: RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleRunwayState: RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTrend: RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_startRemarks: RMK VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_startRemarks matched 'RMK '
DEBUG:metar.Metar:_handleAutoRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePeakWindRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShiftRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleLightningRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTSLocRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp1hrRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip1hrRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip24hrRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePress3hrRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp6hrRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp24hrRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSnowDepthRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleIceAccretionRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark: VIRGA E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark matched 'VIRGA '
DEBUG:metar.Metar:_handleAutoRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePeakWindRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShiftRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleLightningRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTSLocRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp1hrRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip1hrRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip24hrRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePress3hrRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp6hrRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp24hrRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSnowDepthRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleIceAccretionRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark: E TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark matched 'E '
DEBUG:metar.Metar:_handleAutoRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePeakWindRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShiftRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleLightningRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTSLocRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp1hrRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip1hrRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip24hrRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePress3hrRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp6hrRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp24hrRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSnowDepthRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleIceAccretionRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark: TCU NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark matched 'TCU '
DEBUG:metar.Metar:_handleAutoRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePeakWindRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShiftRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleLightningRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTSLocRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp1hrRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip1hrRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip24hrRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePress3hrRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp6hrRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp24hrRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSnowDepthRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleIceAccretionRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark: NE AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark matched 'NE '
DEBUG:metar.Metar:_handleAutoRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePeakWindRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShiftRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleLightningRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTSLocRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp1hrRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip1hrRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip24hrRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePress3hrRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp6hrRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp24hrRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSnowDepthRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleIceAccretionRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark: AND DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark matched 'AND '
DEBUG:metar.Metar:_handleAutoRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePeakWindRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShiftRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleLightningRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTSLocRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp1hrRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip1hrRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip24hrRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handlePress3hrRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp6hrRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp24hrRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleSnowDepthRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_handleIceAccretionRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark: DSNT ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark matched 'DSNT '
DEBUG:metar.Metar:_handleAutoRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handlePeakWindRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleWindShiftRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleLightningRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleTSLocRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp1hrRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip1hrRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handlePrecip24hrRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handlePress3hrRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp6hrRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleTemp24hrRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleSnowDepthRemark: ALQDS SLP186 
DEBUG:metar.Metar:_handleIceAccretionRemark: ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark: ALQDS SLP186 
DEBUG:metar.Metar:_unparsedRemark matched 'ALQDS '
DEBUG:metar.Metar:_handleAutoRemark: SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark: SLP186 
DEBUG:metar.Metar:_handleSealvlPressRemark matched 'SLP186 '
Traceback (most recent call last):
  File "/home/jhaiduce/Development/python-metar/test_metar.py", line 8, in <module>
    Metar.Metar('METAR KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186')
  File "/home/jhaiduce/Development/python-metar/metar/Metar.py", line 498, in __init__
    raise ParserError(message)
metar.Metar.ParserError: Unparsed groups in body '09008KT 7SM' while processing 'METAR KCOF 281855Z FEW029TCU FEW040 SCT250 09008KT 7SM 32/25 A3008 RMK VIRGA E TCU NE AND DSNT ALQDS SLP186'
```

It appears that Metar.py assumes the wind group will come immediately after the modifier, before the sky group. But this METAR violates that assumption, putting the wind group after the sky groups.
