### ISSUE TITLE
parser fails to parse -SNFZDZ

### ISSUE THREAD

**Issue by akrherz** [python-metar/python-metar#90]
current code fails to parse this METAR.

```
>>> from metar.Metar import Metar
>>> report = Metar('KICT 210556Z 01015KT 5SM -SNFZDZ BR OVC014 M08/M09 A3025 RMK AO2 SNB21 SLP261 P0000 60000 T10781094 11050 21078 410281078 51010')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akrherz/projects/python-metar/metar/Metar.py", line 435, in __init__
    raise ParserError(message)
metar.Metar.ParserError: Unparsed groups in body '-SNFZDZ' while processing 'KICT 210556Z 01015KT 5SM -SNFZDZ BR OVC014 M08/M09 A3025 RMK AO2 SNB21 SLP261 P0000 60000 T10781094 11050 21078 410281078 51010'
```

Will have to investigate if `-SNFZDZ` is valid or not.

**Comment by danatobin** [comment]
Another similar issue with this METAR:

METAR KFOE 131345Z 11008KT 1 1/2SM BR-DZ OVC013 00/M02 A3049

It seems like the parser does not like that order of reports (and/or the missing space) per the regular expression. It occurred 3x in a row for this location, then later reports that day are "-DZ BR" which is parsed appropriately. The updated regexp I sent in my email captures this nuance as well.

**Comment by akrherz** [comment]
@danatobin Thanks.  Are you able to submit a Pull Request with your suggested change?
